server:
  port: 9528

spring:
  redis:
    host: localhost
    port: 63790  #可不配，因为底层默认值为6379
  datasource:
    url: jdbc:mysql://localhost:53306/mytest?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml